# Generated by Django 5.0.6 on 2024-06-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variacao',
        ),
    ]
